name: STILL
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 6 * * 0-6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo apt update && sudo apt install desktop-file-utils
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        chmod a+x ./libreoffice-junest.sh
        
        # Determine if LibreOffice release "LOREL" is "still" (default) or "fresh"
        export LOREL="still"
        
        # Determine if language pack set is "base", "standard" or "full"
        export LOLP="base"
        
        # Create "LibreOffice base"
        ./libreoffice-junest.sh
        mkdir dist
        mv *AppImage* dist/ || exit 1
        
        # Create "LibreOffice italian"
        sed -i 's/^#add_italian/add_italian/g' ./libreoffice-junest.sh
        export LOLP="italian"
        ./libreoffice-junest.sh
        mv *AppImage* dist/ || exit 1
                
        # Create "LibreOffice european"
        sed -i 's/^#add_european/add_european/g' ./libreoffice-junest.sh
        export LOLP="european"
        ./libreoffice-junest.sh
        mv *AppImage* dist/ || exit 1
                
        # Create "LibreOffice standard"
        sed -i 's/^#add_standard/add_standard/g' ./libreoffice-junest.sh
        export LOLP="standard"
        ./libreoffice-junest.sh
        mv *AppImage* dist/ || exit 1
                
        # Create "LibreOffice all"
        sed -i 's/^#add_all/add_all/g' ./libreoffice-junest.sh
        export LOLP="all"
        ./libreoffice-junest.sh
        mv *AppImage* dist/ || exit 1

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: LibreOffice STILL
            automatic_release_tag: continuous-still
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
